# Generated by Django 3.0.8 on 2020-08-02 13:08

import datetime
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorDetails',
            fields=[
                ('visitor_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('visitor_name', models.CharField(blank=True, max_length=100, null=True)),
                ('visitor_organization', models.CharField(default='Individual', max_length=200)),
                ('visitor_emp_id', models.CharField(blank=True, max_length=20, null=True)),
                ('visitor_phone_num', models.CharField(blank=True, max_length=20, null=True)),
                ('visitor_email_id', models.EmailField(blank=True, max_length=254, null=True)),
                ('visitor_detail_record', models.DateTimeField(auto_now=True)),
                ('visitor_record_bool', models.BooleanField(default=False)),
                ('visitor_alias', models.SlugField(blank=True, null=True)),
            ],
            options={
                'db_table': 'visitor_details',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='VisitorRequestForm',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('visitor_request_details', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('visitor_comments', models.TextField(blank=True, default='Good system', null=True)),
                ('visitor_entry_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('visitor_request_form_bool', models.BooleanField(default=False)),
                ('visitor_exit_time', models.DateTimeField(auto_now=True, null=True)),
                ('visitor_exit_time_bool', models.BooleanField(default=False)),
                ('visitor_request_alias', models.SlugField(blank=True, null=True)),
                ('visitor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visitor_profile.VisitorDetails')),
            ],
            options={
                'db_table': 'visitor_request_form',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='VisitorRequestEmail',
            fields=[
                ('request_email_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('visitor_meeting_start_time', models.TimeField(blank=True, null=True)),
                ('visitor_meeting_end_time', models.TimeField(blank=True, null=True)),
                ('visitor_meeting_end_bool', models.BooleanField(default=False)),
                ('visitor_request_email_record', models.DateTimeField(auto_now=True)),
                ('visitor_meeting_end_record', models.DateTimeField(blank=True, null=True)),
                ('visitor_request_email_alias', models.SlugField(blank=True, null=True)),
                ('emp_s_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_profile.EmployeeRecord')),
                ('request_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='visitor_profile.VisitorRequestForm')),
            ],
            options={
                'db_table': 'visitor_request_email',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='VisitorInTime',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('visitor_image', models.ImageField(upload_to='static/master_dataset/')),
                ('visitor_image_date_record', models.DateField(verbose_name=datetime.date(2020, 8, 2))),
                ('visitor_image_time_record', models.TimeField(verbose_name=datetime.time(13, 8, 10, 500744))),
                ('visitor_image_record_bool', models.BooleanField(default=False)),
                ('visitor_image_alias', models.SlugField(blank=True, null=True)),
                ('visitor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visitor_profile.VisitorDetails')),
            ],
            options={
                'db_table': 'visitor_in_time',
                'managed': True,
            },
        ),
    ]
