# Generated by Django 3.0.8 on 2020-08-03 20:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor_profile', '0002_auto_20200802_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitorintime',
            name='visitor_image_date_record',
            field=models.DateField(verbose_name=datetime.date(2020, 8, 3)),
        ),
        migrations.AlterField(
            model_name='visitorintime',
            name='visitor_image_time_record',
            field=models.TimeField(verbose_name=datetime.time(20, 35, 43, 609761)),
        ),
    ]
