# Generated by Django 3.0.8 on 2020-08-03 22:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor_profile', '0005_auto_20200803_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitorintime',
            name='visitor_image_time_record',
            field=models.TimeField(verbose_name=datetime.time(22, 24, 57, 158211)),
        ),
    ]
