# Generated by Django 3.0.8 on 2020-08-03 23:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor_profile', '0006_auto_20200803_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitorintime',
            name='visitor_image_date_record',
            field=models.DateField(default=datetime.date(2020, 8, 3)),
        ),
        migrations.AlterField(
            model_name='visitorintime',
            name='visitor_image_time_record',
            field=models.TimeField(default=datetime.time(23, 21, 58, 828064)),
        ),
    ]
