# Generated by Django 3.0.8 on 2020-08-04 11:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor_profile', '0007_auto_20200803_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitorintime',
            name='visitor_image_date_record',
            field=models.DateField(default=datetime.date(2020, 8, 4)),
        ),
        migrations.AlterField(
            model_name='visitorintime',
            name='visitor_image_time_record',
            field=models.TimeField(default=datetime.time(11, 34, 36, 556228)),
        ),
    ]
