# Generated by Django 3.0.8 on 2020-08-04 11:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor_profile', '0008_auto_20200804_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitorintime',
            name='visitor_image_time_record',
            field=models.TimeField(default=datetime.time(11, 39, 0, 635751)),
        ),
    ]
