# Generated by Django 3.0 on 2020-08-04 22:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor_profile', '0009_auto_20200804_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitorintime',
            name='visitor_image_time_record',
            field=models.TimeField(default=datetime.time(22, 20, 45, 239087)),
        ),
    ]
