# Generated by Django 3.0 on 2020-08-11 12:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor_profile', '0016_auto_20200811_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitorintime',
            name='visitor_image_time_record',
            field=models.TimeField(default=datetime.time(12, 35, 48, 803979)),
        ),
    ]
