# Generated by Django 3.0.8 on 2020-08-17 22:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor_profile', '0018_auto_20200811_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitorintime',
            name='visitor_image_date_record',
            field=models.DateField(default=datetime.date(2020, 8, 17)),
        ),
        migrations.AlterField(
            model_name='visitorintime',
            name='visitor_image_time_record',
            field=models.TimeField(default=datetime.time(22, 18, 11, 304383)),
        ),
    ]
