# Generated by Django 3.0.8 on 2020-08-02 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDeptIncharge',
            fields=[
                ('dept_incharge_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('dept_incharge_from', models.DateField()),
                ('dept_incharge_to', models.DateField(blank=True, null=True)),
                ('dept_incharge_record', models.DateTimeField(auto_now_add=True)),
                ('dept_incharge_record_last_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'company_dept_incharge',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CompanyDepts',
            fields=[
                ('dept_s_num', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('dept_id', models.CharField(max_length=20, unique=True)),
                ('dept_name', models.CharField(max_length=20)),
                ('dept_description', models.TextField()),
                ('dept_record', models.DateTimeField(auto_now_add=True)),
                ('dept_status', models.BooleanField(default=True)),
                ('dept_alias', models.SlugField(default='dept', max_length=20, unique=True)),
                ('dept_record_last_modification', models.DateTimeField(auto_now=True)),
                ('dept_logo', models.ImageField(blank=True, max_length=1000, null=True, upload_to='static/master_dataset/')),
            ],
            options={
                'db_table': 'company_dept',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CompanyDetails',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('company_name', models.CharField(max_length=100)),
                ('company_founding_date', models.DateField()),
                ('company_CIN_num', models.CharField(max_length=20, unique=True)),
                ('company_ceo', models.CharField(max_length=100)),
                ('company_billing_address', models.TextField()),
                ('company_telephone', models.CharField(max_length=20)),
                ('company_email', models.EmailField(default='example@email.com', max_length=100)),
                ('company_logo', models.ImageField(max_length=1500, upload_to='static/master_dataset/')),
                ('company_record', models.DateTimeField(auto_now_add=True)),
                ('company_status', models.BooleanField(default=True)),
                ('company_record_last_modification', models.DateTimeField(auto_now=True)),
                ('company_alias', models.SlugField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'company_details',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CompanySiteIncharge',
            fields=[
                ('site_incharge_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('site_incharge_from', models.DateField()),
                ('site_incharge_to', models.DateField(blank=True, null=True)),
                ('site_incharge_record', models.DateTimeField(auto_now=True)),
                ('site_incharge_record_last_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'company_site_incharge',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CompanySites',
            fields=[
                ('site_s_num', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('site_id', models.CharField(max_length=20)),
                ('site_GST_num', models.CharField(default=0, max_length=20)),
                ('site_name', models.CharField(max_length=50)),
                ('site_address', models.TextField()),
                ('site_telephone', models.CharField(max_length=20)),
                ('site_record', models.DateTimeField(auto_now_add=True)),
                ('site_status', models.BooleanField(default=True)),
                ('site_alias', models.SlugField(max_length=20, unique=True)),
                ('site_record_last_modification', models.DateTimeField(auto_now=True)),
                ('company_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company_profile.CompanyDetails')),
            ],
            options={
                'db_table': 'company_sites',
                'managed': True,
            },
        ),
    ]
