# Generated by Django 3.0.8 on 2020-08-02 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee_profile', '0001_initial'),
        ('company_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysiteincharge',
            name='emp_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_profile.EmployeeRecord'),
        ),
        migrations.AddField(
            model_name='companysiteincharge',
            name='site_s_num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_profile.CompanySites'),
        ),
        migrations.AddField(
            model_name='companydepts',
            name='company_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company_profile.CompanyDetails'),
        ),
        migrations.AddField(
            model_name='companydepts',
            name='site_s_num',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company_profile.CompanySites'),
        ),
        migrations.AddField(
            model_name='companydeptincharge',
            name='dept_s_num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_profile.CompanyDepts'),
        ),
        migrations.AddField(
            model_name='companydeptincharge',
            name='emp_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_profile.EmployeeRecord'),
        ),
    ]
