# Generated by Django 3.0.8 on 2020-08-03 20:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_profile', '0002_auto_20200802_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeintime',
            name='emp_entry_date',
            field=models.DateField(default=datetime.date(2020, 8, 3)),
        ),
        migrations.AlterField(
            model_name='employeeintime',
            name='emp_entry_time',
            field=models.TimeField(default=datetime.time(20, 35, 43, 594115)),
        ),
        migrations.AlterField(
            model_name='employeeintime',
            name='emp_s_num',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee_profile.EmployeeRecord'),
        ),
    ]
