# Generated by Django 3.0.8 on 2020-08-02 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0002_auto_20200802_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydetails',
            name='company_alias',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
