# Generated by Django 3.0.8 on 2020-08-17 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0005_auto_20200817_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydepts',
            name='company_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='company_profile.CompanyDetails'),
        ),
    ]
