# Generated by Django 3.0.8 on 2020-08-03 23:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_profile', '0006_auto_20200803_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeintime',
            name='emp_entry_time',
            field=models.TimeField(default=datetime.time(23, 21, 58, 812456)),
        ),
    ]
