# Generated by Django 3.0 on 2020-08-11 12:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_profile', '0015_auto_20200811_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeintime',
            name='emp_entry_date',
            field=models.DateField(default=datetime.date(2020, 8, 11)),
        ),
    ]
