# Generated by Django 3.0.8 on 2020-08-17 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_profile', '0017_auto_20200811_1238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeattendanceverification',
            old_name='attendance_out_time',
            new_name='attendance_time',
        ),
        migrations.RemoveField(
            model_name='employeeattendanceverification',
            name='entry_s_num',
        ),
        migrations.AddField(
            model_name='employeeattendanceverification',
            name='emp_entry_type',
            field=models.CharField(default='I', max_length=1),
        ),
        migrations.AlterModelTable(
            name='employeeattendanceverification',
            table='employee_attendance',
        ),
        migrations.DeleteModel(
            name='EmployeeInTime',
        ),
    ]
