# Generated by Django 3.0.8 on 2020-08-02 13:08

import datetime
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeRecord',
            fields=[
                ('emp_s_num', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('emp_id', models.CharField(max_length=10)),
                ('emp_name', models.CharField(max_length=100)),
                ('emp_gender', models.CharField(max_length=1)),
                ('emp_dob', models.DateField(blank=True, null=True)),
                ('emp_mark_of_identification', models.TextField(default=0)),
                ('emp_AADHAR_num', models.FileField(max_length=1000, upload_to='static/master_dataset/')),
                ('emp_PAN_card', models.FileField(max_length=1000, upload_to='static/master_dataset/')),
                ('emp_bank_account_num', models.FileField(max_length=1000, upload_to='static/master_dataset/')),
                ('emp_family_details', django.contrib.postgres.fields.jsonb.JSONField()),
                ('emp_address', models.TextField(default={})),
                ('emp_personal_email', models.EmailField(default='ishirajk1994@gmail.com', max_length=254)),
                ('emp_personal_phone', models.CharField(default=0, max_length=15)),
                ('emp_doj', models.DateField()),
                ('emp_company_email', models.EmailField(default='ishita.katyal@paritysystems.in', max_length=254)),
                ('emp_education_qualifications', django.contrib.postgres.fields.jsonb.JSONField()),
                ('emp_designation', django.contrib.postgres.fields.jsonb.JSONField()),
                ('emp_leaves_max', models.IntegerField(default=0)),
                ('emp_band', models.CharField(choices=[('B1', 'Band-1'), ('B2', 'Band-2'), ('B3', 'Band-3')], max_length=50)),
                ('emp_record', models.DateTimeField(auto_now_add=True)),
                ('emp_status', models.BooleanField(default=True)),
                ('emp_resigning_date', models.DateField(blank=True, null=True)),
                ('emp_alias', models.SlugField(blank=True, null=True, unique=True)),
                ('emp_record_last_modification_date', models.DateTimeField(auto_now=True)),
                ('company_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company_profile.CompanyDetails')),
                ('dept_s_num', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company_profile.CompanyDepts')),
                ('site_s_num', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company_profile.CompanySites')),
            ],
            options={
                'db_table': 'employee_record',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MoralLines',
            fields=[
                ('moral_line_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('moral_line_text', models.TextField(max_length=500)),
            ],
            options={
                'db_table': 'moral_line',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EmployeeVoice',
            fields=[
                ('voice_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('moral_line_id', models.CharField(blank=True, default='0', max_length=5, null=True)),
                ('emp_voice', models.FileField(blank=True, max_length=500, null=True, upload_to='static/master_dataset/')),
                ('emp_voice_record', models.DateTimeField(auto_now=True)),
                ('emp_voice_alias', models.SlugField(blank=True, null=True)),
                ('emp_s_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_profile.EmployeeRecord')),
            ],
            options={
                'db_table': 'employee_voice',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EmployeeInTime',
            fields=[
                ('entry_s_num', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('emp_entry_date', models.DateField(auto_now=True)),
                ('emp_entry_time', models.TimeField(default=datetime.time(13, 8, 10, 485118))),
                ('emp_entry_type', models.CharField(default='A', max_length=1)),
                ('emp_exit_bool', models.BooleanField(default=False)),
                ('emp_s_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_profile.EmployeeRecord')),
            ],
            options={
                'db_table': 'employee_in_time',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EmployeeAttendanceVerification',
            fields=[
                ('attendance_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('attendance_out_time', models.TimeField(auto_now_add=True, null=True)),
                ('emp_attendance_verified_status', models.BooleanField(default=False)),
                ('emp_attendance_verified_record_time', models.DateTimeField(auto_now=True)),
                ('emp_s_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_profile.EmployeeRecord')),
                ('entry_s_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_profile.EmployeeInTime')),
            ],
            options={
                'db_table': 'employee_out_time_verification',
                'managed': True,
            },
        ),
    ]
