# Generated by Django 3.0 on 2020-08-04 23:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_profile', '0011_auto_20200804_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeintime',
            name='emp_entry_time',
            field=models.TimeField(default=datetime.time(23, 40, 29, 157049)),
        ),
    ]
